incompatible_items = [["Guinsoos_Rageblade_item.png", "Infinity_Edge_item.png"],
                      ["Ravenous_Hydra_item.png", "Titanic_Hydra_item.png"],
                      ["Seryldas_Grudge_item.png", "Lord_Dominiks_Regards_item.png"],
                      ["Maw_of_Malmortius_item.png", "Steraks_Gage_item.png"],
                      ["Silvermere_Dawn_item.png", "Mercurial_Scimitar_item.png"],
                      ["Archangels_Staff_item.png", "Manamune_item.png", "Winters_Approach_item.png"]]

range_champion = ["Ahri.png", "Akshan.png", "Anivia.png",
                  "Annie.png", "Aphelios.png", "Ashe.png",
                  "AurelionSol.png", "Azir.png", "Bard.png",
                  "Brand.png", "Caitlyn.png", "Cassiopeia.png",
                  "Corki.png", "Draven.png", "Elise.png",
                  "Ezreal.png",
                  "Fiddlesticks.png", "Gnar.png", "Graves.png",
                  "Heimerdinger.png", "Ivern.png", "Janna.png",
                  "Jayce.png", "Jhin.png", "Jinx.png",
                  "Kaisa.png",
                  "Kalista.png", "Karma.png", "Karthus.png",
                  "Kayle.png", "Kennen.png", "Kindred.png",
                  "KogMaw.png", "Leblanc.png", "Lillia.png",
                  "Lissandra.png",
                  "Lucian.png", "Lulu.png", "Lux.png",
                  "Malzahar.png", "MissFortune.png",
                  "Morgana.png", "Nami.png", "Neeko.png",
                  "Nidalee.png", "Orianna.png",
                  "Quinn.png", "Rakan.png", "Renata.png",
                  "Ryze.png", "Samira.png", "Senna.png",
                  "Seraphine.png", "Sivir.png", "Sona.png",
                  "Soraka.png", "Swain.png",
                  "Syndra.png", "Taliyah.png", "Teemo.png",
                  "Thresh.png", "Tristana.png",
                  "TwistedFate.png", "Twitch.png", "Urgot.png",
                  "Varus.png", "Vayne.png",
                  "Veigar.png", "Velkoz.png", "Vex.png",
                  "Viktor.png", "Vladimir.png", "Xayah.png",
                  "Xerath.png", "Yuumi.png", "Zeri.png",
                  "Ziggs.png", "Zilean.png",
                  "Zoe.png", "Zyra.png"]

melee_champion = ['Aatrox.png', 'Akali.png', 'Alistar.png', 'Amumu.png', 'belveth.png', 'Blitzcrank.png', 'Braum.png', 'Camille.png', 'ChoGath.png', 'Darius.png', 'Diana.png', 'DrMundo.png', 'Ekko.png', 'Evelynn.png', 'Fiora.png', 'Fizz.png', 'Galio.png', 'Gangplank.png', 'Garen.png', 'Gragas.png', 'Gwen.png', 'Hecarim.png', 'Illaoi.png', 'Irelia.png', 'JarvanIV.png', 'Jax.png', 'karthus.png', 'Kassadin.png', 'Katarina.png', 'Kayn.png', 'Khazix.png', 'Kled.png', 'LeeSin.png', 'Leona.png', 'Malphite.png', 'Maokai.png', 'MasterYi.png', 'Mordekaiser.png', 'Nasus.png', 'Nautilus.png', 'Nocturne.png', 'Nunu.png', 'Olaf.png', 'Ornn.png', 'Pantheon.png', 'Poppy.png', 'Pyke.png', 'Qiyana.png', 'Rammus.png', 'RekSai.png', 'Rell.png', 'Renekton.png', 'Rengar.png', 'Riven.png', 'Rumble.png', 'Sejuani.png', 'Sett.png', 'Shaco.png', 'Shen.png', 'Shyvana.png', 'Singed.png', 'Sion.png', 'Skarner.png', 'Sylas.png', 'TahmKench.png', 'Talon.png', 'Taric.png', 'Trundle.png', 'Tryndamere.png', 'Udyr.png', 'Vi.png', 'Viego.png', 'Volibear.png', 'Warwick.png', 'Wukong.png', 'XinZhao.png', 'Yasuo.png', 'Yone.png', 'Yorick.png', 'Zac.png', 'Zed.png', "Nilah.png"]