incompatible_items = [["Guinsoos_Rageblade_item.png", "Infinity_Edge_item.png"],
                      ["Ravenous_Hydra_item.png", "Titanic_Hydra_item.png"],
                      ["Seryldas_Grudge_item.png", "Lord_Dominiks_Regards_item.png"],
                      ["Maw_of_Malmortius_item.png", "Steraks_Gage_item.png"],
                      ["Silvermere_Dawn_item.png", "Mercurial_Scimitar_item.png"],
                      ["Archangels_Staff_item.png", "Manamune_item.png", "Winters_Approach_item.png"]]

range_champion = ["Ahri.png", "Akshan.png", "Anivia.png",
                  "Annie.png", "Aphelios.png", "Ashe.png",
                  "AurelionSol.png", "Azir.png", "Bard.png",
                  "Brand.png", "Caitlyn.png", "Cassiopeia.png",
                  "Corki.png", "Draven.png", "Elise.png",
                  "Ezreal.png",
                  "Fiddlesticks.png", "Gnar.png", "Graves.png",
                  "Heimerdinger.png", "Ivern.png", "Janna.png",
                  "Jayce.png", "Jhin.png", "Jinx.png",
                  "Kaisa.png",
                  "Kalista.png", "Karma.png", "Karthus.png",
                  "Kayle.png", "Kennen.png", "Kindred.png",
                  "KogMaw.png", "Leblanc.png", "Lillia.png",
                  "Lissandra.png",
                  "Lucian.png", "Lulu.png", "Lux.png",
                  "Malzahar.png", "MissFortune.png",
                  "Morgana.png", "Nami.png", "Neeko.png",
                  "Nidalee.png", "Orianna.png",
                  "Quinn.png", "Rakan.png", "Renata.png",
                  "Ryze.png", "Samira.png", "Senna.png",
                  "Seraphine.png", "Sivir.png", "Sona.png",
                  "Soraka.png", "Swain.png",
                  "Syndra.png", "Taliyah.png", "Teemo.png",
                  "Thresh.png", "Tristana.png",
                  "TwistedFate.png", "Twitch.png", "Urgot.png",
                  "Varus.png", "Vayne.png",
                  "Veigar.png", "Velkoz.png", "Vex.png",
                  "Viktor.png", "Vladimir.png", "Xayah.png",
                  "Xerath.png", "Yuumi.png", "Zeri.png",
                  "Ziggs.png", "Zilean.png",
                  "Zoe.png", "Zyra.png"]
