incompatible_items = {
    "Archangels_Staff_item.png": ["Winters_Approach_item.png", "Manamune_item.png", "Maw_Of_Malmortius_item.png", "Steraks_Gage_item.png"],
    "Winters_Approach_item.png": ["Archangels_Staff_item.png", "Manamune_item.png"],
    "Manamune_item.png": ["Winters_Approach_item.png", "Archangels_Staff_item.png"],
    "Titanic_Hydra_item.png": ["Ravenous_Hydra_item.png"],
    "Spear_Of_Shojin_item.png": ["Navori_Quickblades_item.png"],
    "Mercurial_Scimitar_item.png": ["Silvermere_dawn_item.png"],
    "Silvermere_dawn_item.png": ["Mercurial_Scimitar_item.png"],
    "Maw_Of_Malmortius_item.png": ["Steraks_Gage_item.png", "Immortal_Shieldbow_item.png"],
    "Steraks_Gage_item.png": ["Maw_Of_Malmortius_item.png", "Immortal_Shieldbow_item.png"],
    "Immortal_Shieldbow_item.png": ["Maw_Of_Malmortius_item.png", "Steraks_Gage_item.png"],
    "Ravenous_Hydra_item.png": ["Titanic_Hydra_item.png"],
    "Seryldas_Grudge_item.png": ["Lord_Dominiks_Regards_item.png", "Mortal_Reminder_item.png"],
    "Lord_Dominiks_Regards_item.png": ["Seryldas_Grudge_item.png", "Mortal_Reminder_item.png"],
    "Mortal_Reminder_item.png": ["Seryldas_Grudge_item.png", "Lord_Dominiks_Regards_item.png"]
}


champions = [
    "Aatrox",
    "Ahri",
    "Akali",
    "Akshan",
    "Alistar",
    "Amumu",
    "Anivia",
    "Annie",
    "Aphelios",
    "Ashe",
    "Aurelion Sol",
    "Azir",
    "Bard",
    "Belveth",
    "Blitzcrank",
    "Briar",
    "Brand",
    "Braum",
    "Caitlyn",
    "Camille",
    "Cassiopeia",
    "Cho'Gath",
    "Corki",
    "Darius",
    "Diana",
    "Draven",
    "Dr.Mundo",
    "Ekko",
    "Elise",
    "Evelynn",
    "Ezreal",
    "Fiddlesticks",
    "Fiora",
    "Fizz",
    "Galio",
    "Gangplank",
    "Garen",
    "Gnar",
    "Gragas",
    "Graves",
    "Gwen",
    "Hecarim",
    "Heimerdinger",
    "Illaoi",
    "Irelia",
    "Ivern",
    "Janna",
    "JarvanIV",
    "Jax",
    "Jayce",
    "Jhin",
    "Jinx",
    "Kai'sa",
    "Kalista",
    "Karma",
    "Karthus",
    "Karthus",
    "Kassadin",
    "Katarina",
    "Kayle",
    "Kayn",
    "Kennen",
    "Kha'zix",
    "Kindred",
    "Kled",
    "Kog'Maw",
    "K'Sante",
    "LeBlanc",
    "Lee sin",
    "Leona",
    "Lillia",
    "Lissandra",
    "Lucian",
    "Lulu",
    "Lux",
    "Malphite",
    "Malzahar",
    "Maokai",
    "Masteryi",
    "Miss Fortune",
    "Mordekaiser",
    "Morgana",
    "Nami",
    "Nasus",
    "Nautilus",
    "Neeko",
    "Nidalee",
    "Nilah",
    "Nocturne",
    "Nunu",
    "Olaf",
    "Orianna",
    "Ornn",
    "Pantheon",
    "Poppy",
    "Pyke",
    "Qiyana",
    "Quinn",
    "Rakan",
    "Rammus",
    "Rek'sai",
    "Rell",
    "Renata",
    "Renekton",
    "Rengar",
    "Riven",
    "Rumble",
    "Ryze",
    "Samira",
    "Sejuani",
    "Senna",
    "Seraphine",
    "Sett",
    "Shaco",
    "Shen",
    "Shyvana",
    "Singed",
    "Sion",
    "Sivir",
    "Skarner",
    "Sona",
    "Soraka",
    "Swain",
    "Sylas",
    "Syndra",
    "Tahmkench",
    "Taliyah",
    "Talon",
    "Taric",
    "Teemo",
    "Thresh",
    "Tristana",
    "Trundle",
    "Tryndamere",
    "Twisted Fate",
    "Twitch",
    "Udyr",
    "Urgot",
    "Varus",
    "Vayne",
    "Veigar",
    "Vel'koz",
    "Vex",
    "Vi",
    "Viego",
    "Viktor",
    "Vladimir",
    "Volibear",
    "Warwick",
    "Wukong",
    "Xayah",
    "Xerath",
    "Xin Zhao",
    "Yasuo",
    "Yone",
    "Yorick",
    "Yuumi",
    "Zac",
    "Zed",
    "Zeri",
    "Ziggs",
    "Zilean",
    "Zoe",
    "Zyra",
]

range_champion = ["ahri.png", "akshan.png", "anivia.png",
                  "annie.png", "aphelios.png", "ashe.png",
                  "aurelionsol.png", "azir.png", "bard.png",
                  "brand.png", "caitlyn.png", "cassiopeia.png",
                  "corki.png", "draven.png", "elise.png",
                  "ezreal.png",
                  "fiddlesticks.png", "gnar.png", "graves.png",
                  "heimerdinger.png", "ivern.png", "janna.png",
                  "jayce.png", "jhin.png", "jinx.png",
                  "kaisa.png",
                  "kalista.png", "karma.png", "karthus.png",
                  "kayle.png", "kennen.png", "kindred.png",
                  "kogmaw.png", "leblanc.png", "lillia.png",
                  "lissandra.png",
                  "lucian.png", "lulu.png", "lux.png",
                  "malzahar.png", "missfortune.png",
                  "milio.png"
                  "morgana.png", "nami.png", "neeko.png",
                  "nidalee.png", "orianna.png",
                  "quinn.png", "rakan.png", "renata.png",
                  "ryze.png", "samira.png", "senna.png",
                  "seraphine.png", "sivir.png", "sona.png",
                  "soraka.png", "swain.png",
                  "syndra.png", "taliyah.png", "teemo.png",
                  "thresh.png", "tristana.png",
                  "twistedfate.png", "twitch.png", "urgot.png",
                  "varus.png", "vayne.png",
                  "veigar.png", "velkoz.png", "vex.png",
                  "viktor.png", "vladimir.png", "xayah.png",
                  "xerath.png", "yuumi.png", "zeri.png",
                  "ziggs.png", "zilean.png",
                  "zoe.png", "zyra.png"]

melee_champion = ["aatrox.png", "akali.png", "alistar.png",
                  "amumu.png", "belveth.png", "blitzcrank.png",
                  "briar.png",
                  "braum.png", "camille.png", "chogath.png",
                  "darius.png", "diana.png", "drmundo.png",
                  "ekko.png", "evelynn.png", "fiora.png",
                  "fizz.png", "galio.png", "gangplank.png",
                  "garen.png", "gragas.png", "gwen.png",
                  "hecarim.png", "illaoi.png", "irelia.png",
                  "jarvaniv.png", "jax.png", "karthus.png",
                  "kassadin.png", "katarina.png", "kayn.png",
                  "khazix.png", "kled.png", "leesin.png",
                  "leona.png", "malphite.png", "maokai.png",
                  "masteryi.png", "mordekaiser.png", "nasus.png",
                  "nautilus.png", "nocturne.png", "nunu.png",
                  "olaf.png", "ornn.png", "pantheon.png",
                  "poppy.png", "pyke.png", "qiyana.png",
                  "rammus.png", "reksai.png", "rell.png",
                  "renekton.png", "rengar.png", "riven.png",
                  "rumble.png", "sejuani.png", "sett.png",
                  "shaco.png", "shen.png", "shyvana.png",
                  "singed.png", "sion.png", "skarner.png",
                  "sylas.png", "tahmkench.png", "talon.png",
                  "taric.png", "trundle.png", "tryndamere.png",
                  "udyr.png", "vi.png", "viego.png",
                  "volibear.png", "warwick.png", "wukong.png",
                  "xinzhao.png", "yasuo.png", "yone.png",
                  "yorick.png", "zac.png", "zed.png",
                  "nilah.png", "ksante.png"]